### ISSUE TITLE
Composite rules

### ISSUE THREAD

**Issue by PierreDemailly** [MyUnisoft/sigyn#106]
The idea of this feature is to be able to have a rule (or multiple rules) based on rules.

Example: rule foo and rule bar triggers 50 times in 15 minutes: triggers a compositeRule alert.

Example config:
```json
...
"rules": [
  ...
],
"compositeRules": [
  {
    "name": "A composite rule based on each production rules",
    "include": ["PROD*"],
    "exclude": ["PROD - not critical rule"],
    "notifCount": 50,
    "interval": "15m",
    "template": "foo"
    "notifiers": ["discord"],
    "throttle": { "interval": "30m" }
  }
]
...
```

Notes & questions:
- Is the property name `compositeRules` accurate ?
- What would be the **required** fields ? I would say: `name` (as unique identifier), `notifCount`, and `template`. 
- A bit off topic but i'm thinking to notifiers. For me it should not be required with the same behavior as `rules`: if not specified we takes all notifiers. And I wonder if we should add some config directly to the root `notifiers` field. Especially with #102, we probably want `rules` notifiers, `selfMonitoring` notifiers and so `compositeRules` notifiers.
  > [!NOTE]
  > Actually, `selfMonitoring.notifiers` is **required**, I think its a mistake

  I would see a config like that:
  ```json
  "notifiers": {
    "discord": {
      "scope": ["selfMonitoring", "rules"],
      "notifier": "discord",
      "webhookUrl": "https://discord.com/api/webhooks/aaa/bbb"
    },
    "another-discord": {
      "scope": ["compositeRules"]
      "notifier": "discord",
      "webhookUrl": "https://discord.com/api/webhooks/ccc/ddd"
    },
  }
  ```
  The idea is to be able to scope the notifiers so  `rule.notifiers`, `selfMonitoring.notifiers` & `compositeRule.notifier` become almost useless (should be only used for special case).
- What vars are available for the template ? It could be `notifCount` + `compositeRules` (which would be same as `agentFailure.rules` with self-monitoring).
If the composite rule is based on a large number of rules, the number of label could be very high, i don't see how we could provide a `lokiUrl`, etc
- Should we prevent multiple equal compositeRule or is it user responsability ? (i.e. multiple compositeRules without `include` & `exclude` makes no sense.
- Should we disable rules that triggers the compositeRule ? Maybe via a rule option: `disableOnComposite` or via a compositeRule option `disableRules`

**Comment by PierreDemailly** [comment]
@fraxken Do you validate the `scope` idea ?
```json
"notifiers": {
  "discord": {
    "scope": ["selfMonitoring", "rules"],
    "notifier": "discord",
    "webhookUrl": "https://discord.com/api/webhooks/aaa/bbb"
  },
  "another-discord": {
    "scope": ["compositeRules"]
    "notifier": "discord",
    "webhookUrl": "https://discord.com/api/webhooks/ccc/ddd"
  },
}
```
If ok it could be a separate task to be implemented in first place.
(I think i'm gonna work for compositeRule this week end)

**Comment by fraxken** [comment]
@PierreDemailly Why not, but i'm not 100% sure because for me we achieve the same by enforcing the right notifier on rules etc.. 

But I guess for simple config this could help

**Comment by PierreDemailly** [comment]
Yeah i'll skip it for now, we can see later if needed

> we achieve the same by enforcing the right notifier on rules etc..

The goal was exactly to skip theses fields ^^

Imagine the user have ~20 rules with 2 notifiers, all rules have `notifiers` field skipped because alerts need to be sent to theses two notifiers, theses is no `selfMonitoring` or `compositeRules`.
Now user add a composite rule, with a new notifier dedicated to composite rules.
With scope: he just have to deal with scope, at one place
Without scope: he shall update each rules, adding a new `notifiers` field to say "do not send to this new notifier"..

For me its helpful for complex configs with lots of rules and useless for simple configs ^^
