### ISSUE TITLE
Alert on value matching threshold

### ISSUE THREAD

**Issue by fraxken** [MyUnisoft/sigyn#47]
(WIP / Spécification)

Throw an alert if the threshold of a given value exceeds what we expect.

> **note** maybe we should limit to one field at the beginning?

```json
"alert": {
  "on": {
    "match": "state: (ok|ko)",
    "threshold": {
      "ko": ">= 80%"
    }
  }
}
```

To achieve this we need to:
- Execute a RegEx on each logs
- Store another counter

**Comment by PierreDemailly** [comment]
We also need a way to configure a minimum of logs data to be compared (i.e. **4** `ko` for **1** `ok` is 80% but is not revelant)
it could be either an `interval` (a big one e.g. `20d`) or a `count` ?

**Comment by fraxken** [comment]
@PierreDemailly Yes I was thinking about combining with a count (to avoid unrevelant alerts on a low number of logs).

**Comment by PierreDemailly** [comment]
Based on https://github.com/MyUnisoft/sigyn/issues/50#issuecomment-1684922963
We could simply compare labels, for example we could use this LogQL: ``{env="production", app="foo"} |~ `state: (ok|ko)` | regexp `state: (?P<state>ok|ko)` `` 
Then, each log have a label `state` stored in base
Atm, labels are unique (no duplicates), we could store them all so comparing labels become a simple game, i would see this rule config:
```json
{
  "name": "[Foo] (PROD) State KO >= 80%",
  "logql": "{env=\"production\", app=\"foo\"} |~ `state: (ok|ko)` | regexp `state: (?P<state>ok|ko)`",
  "alert": {
    "on": {
      "label": "state",
      "value": "ko",
      "thresholdPercent": 80
    }
  }  
}
 ```
 (+ `interval` or `count` for a minimum number of logs to be compared, as discussed before)
Wdyt @fraxken ?

**Comment by fraxken** [comment]
@PierreDemailly seems good (not sure the key name however but we can still rename them later).

**Comment by PierreDemailly** [comment]
Another thing we want is a match for **regex equal** / **regex not equal**.
For instance we could triggers an alert for a percentage of statusCode != 20X
