### ISSUE TITLE
Add variable link to explore in Grafana Loki?

### ISSUE THREAD

**Issue by fraxken** [MyUnisoft/sigyn#59]
Add a variable link to explore logs in Grafana Loki (with maybe a time range of 30 minutes ?).

**Comment by PierreDemailly** [comment]
Useful API endpoints:
Short URL: https://grafana.com/docs/grafana/latest/developers/http_api/short_url/
Datasource: https://grafana.com/docs/grafana/latest/developers/http_api/data_source/#get-data-source-id-by-name
Organization: https://grafana.com/docs/grafana/latest/developers/http_api/org/
